import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {

var monsters = ["chaos","octopus","hook","sassquatch"];
// getting a random item from an array of monsters
var randomMonster = monsters[Math.floor(Math.random() * monsters.length)];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">MonsterDex!</a>
        </h1>


        <div className={styles.grid}>
         
          <div className={styles.card}>
          <Link href="/monsters/chaos"
          >
            <a>
              See The first monster.
            </a>
          </Link>
          </div>
          <div className={styles.card}>
          <Link href="/monsters/octopus"
          >
            <a>
              See The Second monster.
            </a>
          </Link>
          </div>
          <div className={styles.card}>
          <Link href="/monsters/hook"
          >
            <a>
              See The Hook monster.
            </a>
          </Link>
          </div>
          <div className={styles.card}>
          <Link href="/monsters/sassquatch"
          >
            <a>
              See The sassquatch.
            </a>
          </Link>
          </div>
          <div className={styles.card}>
          <Link href={"/monsters/" + randomMonster}
          >
            <a>
              Show me a random monster
            </a>
          </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
